### ISSUE TITLE
remark-prism causes deploy fail on Netlify

### ISSUE THREAD

**Issue by karlhorky** [upleveled/next-starter-peacock#23]
Errors deploying to Netlify:

```
3:46:56 PM: $ yarn next build
3:46:56 PM: yarn run v1.22.4
3:46:56 PM: $ /opt/build/repo/node_modules/.bin/next build
3:46:57 PM: info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
3:46:57 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
3:46:57 PM: info  - Checking validity of types...
3:47:01 PM: info  - Creating an optimized production build...
3:47:26 PM: Failed to compile.
3:47:26 PM:
3:47:26 PM: ModuleNotFoundError: Module not found: Error: Can't resolve 'canvas' in '/opt/build/repo/node_modules/jsdom/lib/jsdom'
3:47:26 PM: > Build error occurred
3:47:26 PM: Error: > Build failed because of webpack errors
3:47:27 PM:     at /opt/build/repo/node_modules/next/dist/build/index.js:17:924
3:47:27 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:6:584)
3:47:27 PM: error Command failed with exit code 1.
```

tried `yarn add canvas` (also needed `brew install pkg-config pixman cairo pango`), then another error:

```
4:13:52 PM: $ yarn build
4:13:52 PM: yarn run v1.22.4
4:13:52 PM: $ next build
4:13:53 PM: info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
4:13:53 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
4:13:53 PM: info  - Checking validity of types...
4:13:58 PM: info  - Creating an optimized production build...
4:14:26 PM: Failed to compile.
4:14:26 PM:
4:14:26 PM: ModuleNotFoundError: Module not found: Error: Can't resolve 'bufferutil' in '/opt/build/repo/node_modules/ws/lib'
4:14:26 PM: > Build error occurred
4:14:26 PM: Error: > Build failed because of webpack errors
4:14:26 PM:     at /opt/build/repo/node_modules/next/dist/build/index.js:17:924
4:14:26 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:6:584)
4:14:26 PM: error Command failed with exit code 1.
```

tried `yarn add bufferutil`, then another error:

```
4:16:48 PM: $ yarn build
4:16:48 PM: yarn run v1.22.4
4:16:49 PM: $ next build
4:16:49 PM: info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
4:16:49 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
4:16:49 PM: info  - Checking validity of types...
4:16:53 PM: info  - Creating an optimized production build...
4:17:18 PM: Failed to compile.
4:17:18 PM:
4:17:18 PM: ModuleNotFoundError: Module not found: Error: Can't resolve 'utf-8-validate' in '/opt/build/repo/node_modules/ws/lib'
4:17:18 PM: > Build error occurred
4:17:18 PM: Error: > Build failed because of webpack errors
4:17:18 PM:     at /opt/build/repo/node_modules/next/dist/build/index.js:17:924
4:17:18 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:6:584)
4:17:18 PM: error Command failed with exit code 1.
```

tried `yarn add utf-8-validate`, then another error:

```
4:19:34 PM: $ yarn build
4:19:34 PM: yarn run v1.22.4
4:19:34 PM: $ next build
4:19:35 PM: info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
4:19:35 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
4:19:35 PM: info  - Checking validity of types...
4:19:40 PM: info  - Creating an optimized production build...
4:20:08 PM: (node:1503) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
4:20:22 PM: Failed to compile.
4:20:22 PM:
4:20:22 PM: ./node_modules/canvas/build/Release/canvas.node
4:20:22 PM: Module parse failed: Unexpected character '' (1:0)
4:20:22 PM: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
4:20:22 PM: (Source code omitted for this binary file)
4:20:22 PM: > Build error occurred
4:20:22 PM: Error: > Build failed because of webpack errors
4:20:22 PM:     at /opt/build/repo/node_modules/next/dist/build/index.js:17:924
4:20:22 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:6:584)
4:20:22 PM: error Command failed with exit code 1.
```

set [`externals.canvas = {};`](https://github.com/steiningerjakob/portfolio/commit/cb9a39cdef0442853336ce3bad8d68950a2f2fa8) in webpack config, then another error:

```
4:28:19 PM: $ yarn build
4:28:20 PM: yarn run v1.22.4
4:28:20 PM: $ next build
4:28:21 PM: info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
4:28:21 PM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
4:28:21 PM: info  - Checking validity of types...
4:28:27 PM: info  - Creating an optimized production build...
4:28:50 PM: info  - Compiled successfully
4:28:50 PM: info  - Collecting page data...
4:28:57 PM: info  - Generating static pages (0/28)
4:29:00 PM: Error occurred prerendering page "/articles/tags/javascript". Read more: https://nextjs.org/docs/messages/prerender-error
4:29:00 PM: Error: Module did not self-register: '/opt/build/repo/node_modules/canvas/build/Release/canvas.node'.
4:29:00 PM:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
4:29:00 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
4:29:00 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
4:29:00 PM:     at Module.require (internal/modules/cjs/loader.js:1026:19)
4:29:00 PM:     at require (internal/modules/cjs/helpers.js:72:18)
4:29:00 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/canvas/lib/bindings.js:3:18)
4:29:00 PM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
4:29:00 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
4:29:00 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
4:29:00 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
4:29:00 PM: Error occurred prerendering page "/articles". Read more: https://nextjs.org/docs/messages/prerender-error
4:29:00 PM: Error: Module did not self-register: '/opt/build/repo/node_modules/canvas/build/Release/canvas.node'.
4:29:00 PM:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
4:29:00 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
4:29:00 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
4:29:00 PM:     at Module.require (internal/modules/cjs/loader.js:1026:19)
4:29:00 PM:     at require (internal/modules/cjs/helpers.js:72:18)
4:29:00 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/canvas/lib/bindings.js:3:18)
4:29:00 PM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
4:29:00 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
4:29:00 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
4:29:00 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
4:29:00 PM: Error occurred prerendering page "/works". Read more: https://nextjs.org/docs/messages/prerender-error
4:29:00 PM: Error: Module did not self-register: '/opt/build/repo/node_modules/canvas/build/Release/canvas.node'.
4:29:00 PM:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
4:29:00 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
4:29:00 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
4:29:00 PM:     at Module.require (internal/modules/cjs/loader.js:1026:19)
4:29:00 PM:     at require (internal/modules/cjs/helpers.js:72:18)
4:29:00 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/canvas/lib/bindings.js:3:18)
4:29:00 PM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
4:29:00 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
4:29:00 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
4:29:00 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
4:29:00 PM: Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
4:29:00 PM: Error: Module did not self-register: '/opt/build/repo/node_modules/canvas/build/Release/canvas.node'.
4:29:00 PM:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
4:29:00 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
4:29:00 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
4:29:00 PM:     at Module.require (internal/modules/cjs/loader.js:1026:19)
4:29:00 PM:     at require (internal/modules/cjs/helpers.js:72:18)
4:29:00 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/canvas/lib/bindings.js:3:18)
4:29:00 PM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
4:29:00 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
4:29:00 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
4:29:00 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
```

which may have something to do with the `canvas` module, although not sure how to fix: https://github.com/Automattic/node-canvas/issues/1394

---

Eventually figured out that it has to do with `remark-prism`, removed in this commit: https://github.com/steiningerjakob/portfolio/commit/7de99dd649b2a8cd69fe5ec23f67812b3d771861#diff-ab4a47f482def4256edce1db3cb5d05baa017b8fcc2299b281057da8560d0bd6R111

**Comment by karlhorky** [comment]
@Josehower you can investigate the problem with `jsdom` and the other dependencies of `remark-prism` first quickly, and if you can't figure out a good solution fast, check out these alternatives for syntax highlighting:

- [`remark-highlight.js`](https://github.com/remarkjs/remark-highlight.js)
- [`@stefanprobst/remark-shiki`](https://github.com/stefanprobst/remark-shiki)

**Comment by Josehower** [comment]
One solution to this error that worked for me was changing remark-prism for remark-highlight

I created a PR to solve this

https://github.com/vickOnRails/next-starter-peacock/pull/9

**Comment by Josehower** [comment]
Closing this issue after fixin the problem replacing problematic dependency:

[Commit link](https://github.com/upleveled/next-starter-peacock/commit/daf501093ce9bdb508f6bdbf7e9a691d4516307d)
